//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEntityOkul
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogretmenler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogretmenler()
        {
            this.Sınıflar = new HashSet<Sınıflar>();
        }
    
        public int Id { get; set; }
        public string Adı { get; set; }
        public string Soyadı { get; set; }
        public string Telefon { get; set; }
        public int KursId { get; set; }
    
        public virtual Kurslar Kurslar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sınıflar> Sınıflar { get; set; }
    }
}
