//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEntityOkul
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sınıflar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sınıflar()
        {
            this.Ogrencilers = new HashSet<Ogrenciler>();
        }
    
        public int Id { get; set; }
        public string Adı { get; set; }
        public int OgretmenId { get; set; }
        public int KursId { get; set; }
        public Nullable<System.DateTime> ATarihi { get; set; }
        public Nullable<System.DateTime> KTarihi { get; set; }
        public string Açıklama { get; set; }
    
        public virtual Kurslar Kurslar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ogrenciler> Ogrencilers { get; set; }
        public virtual Ogretmenler Ogretmenler { get; set; }
    }
}
